/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital_management_system;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mr. Sultan
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        doctorPanel = new javax.swing.JPanel();
        DoctorLbl = new javax.swing.JLabel();
        patientPanel = new javax.swing.JPanel();
        patientLbl = new javax.swing.JLabel();
        madicinesPanel = new javax.swing.JPanel();
        medicinesLbl = new javax.swing.JLabel();
        laboratoryPanel = new javax.swing.JPanel();
        LaboratoryLbl = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        facilitiesPanel = new javax.swing.JPanel();
        FacilitiesLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorPanel.setBackground(new java.awt.Color(0, 102, 102));
        doctorPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        doctorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorPanelMouseClicked(evt);
            }
        });
        doctorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DoctorLbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        DoctorLbl.setForeground(new java.awt.Color(255, 255, 255));
        DoctorLbl.setText("Doctor");
        doctorPanel.add(DoctorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jPanel3.add(doctorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 150, 40));

        patientPanel.setBackground(new java.awt.Color(0, 102, 102));
        patientPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientPanelMouseClicked(evt);
            }
        });
        patientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientLbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        patientLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientLbl.setText("Patients");
        patientPanel.add(patientLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        jPanel3.add(patientPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 150, 40));

        madicinesPanel.setBackground(new java.awt.Color(0, 102, 102));
        madicinesPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        madicinesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                madicinesPanelMouseClicked(evt);
            }
        });
        madicinesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicinesLbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        medicinesLbl.setForeground(new java.awt.Color(255, 255, 255));
        medicinesLbl.setText("Madicines");
        madicinesPanel.add(medicinesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jPanel3.add(madicinesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 150, -1));

        laboratoryPanel.setBackground(new java.awt.Color(0, 102, 102));
        laboratoryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laboratoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laboratoryPanelMouseClicked(evt);
            }
        });
        laboratoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LaboratoryLbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        LaboratoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        LaboratoryLbl.setText("Laboratory");
        laboratoryPanel.add(LaboratoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        jPanel3.add(laboratoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 40));

        exitPanel.setBackground(new java.awt.Color(0, 102, 102));
        exitPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanelMouseClicked(evt);
            }
        });
        exitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(0, 51, 51));
        exitBtn.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        exitPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jPanel3.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 150, 60));

        facilitiesPanel.setBackground(new java.awt.Color(0, 102, 102));
        facilitiesPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        facilitiesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facilitiesPanelMouseClicked(evt);
            }
        });
        facilitiesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FacilitiesLbl.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        FacilitiesLbl.setForeground(new java.awt.Color(255, 255, 255));
        FacilitiesLbl.setText("Facilities");
        facilitiesPanel.add(FacilitiesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jPanel3.add(facilitiesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-images/hospital management Manu.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 560));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
////============================
    //Here we code of doctor section to access from main menu
//============================
    private void doctorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorPanelMouseClicked
        try {
            // TODO add your handling code here:
            Doctor doc = new Doctor();// object
            this.setVisible(false);
            doc.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Main_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_doctorPanelMouseClicked
//============================
    //Here we code of Medicienes section to access from main menu
//============================
    private void madicinesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_madicinesPanelMouseClicked
        // TODO add your handling code here:
        Medicienes med = new Medicienes();// Object
        this.setVisible(false);
        med.setVisible(true);

    }//GEN-LAST:event_madicinesPanelMouseClicked
//============================
    //Here we code of Patients section to access from main menu
//============================
    private void patientPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientPanelMouseClicked
        // TODO add your handling code here:
        patients pat = new patients();// Object
        this.setVisible(false);
        pat.setVisible(true);

    }//GEN-LAST:event_patientPanelMouseClicked
//============================
    //Here we code of Laboratory section to access from main menu
//============================
    private void laboratoryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboratoryPanelMouseClicked
        // TODO add your handling code here:
        Laboratory lab = new Laboratory();// Object
        this.setVisible(false);
        lab.setVisible(true);
    }//GEN-LAST:event_laboratoryPanelMouseClicked
//============================
    //Here we code of Facilities section to access from main menu
//============================
    private void exitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseClicked
        // TODO add your handling code here:
        Facilities fac = new Facilities();// Object
        this.setVisible(false);
        fac.setVisible(true);

    }//GEN-LAST:event_exitPanelMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Exit button
    }//GEN-LAST:event_exitBtnActionPerformed

    private void facilitiesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facilitiesPanelMouseClicked
  Facilities faci = new Facilities();// Object
        this.setVisible(false);
        faci.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_facilitiesPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorLbl;
    private javax.swing.JLabel FacilitiesLbl;
    private javax.swing.JLabel LaboratoryLbl;
    private javax.swing.JPanel doctorPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel facilitiesPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel laboratoryPanel;
    private javax.swing.JPanel madicinesPanel;
    private javax.swing.JLabel medicinesLbl;
    private javax.swing.JLabel patientLbl;
    private javax.swing.JPanel patientPanel;
    // End of variables declaration//GEN-END:variables
}
